
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.role
{
public sealed partial class RoleRes : Luban.BeanBase
{
    public RoleRes(JSONNode _buf) 
    {
        { if(!_buf["Id"].IsNumber) { throw new SerializationException(); }  Id = _buf["Id"]; }
        { if(!_buf["Name"].IsString) { throw new SerializationException(); }  Name = _buf["Name"]; }
        { if(!_buf["Prefab"].IsString) { throw new SerializationException(); }  Prefab = _buf["Prefab"]; }
        { if(!_buf["HeadIcon"].IsString) { throw new SerializationException(); }  HeadIcon = _buf["HeadIcon"]; }
        { var __json0 = _buf["AnimationClips"]; if(!__json0.IsArray) { throw new SerializationException(); } AnimationClips = new System.Collections.Generic.Dictionary<string, string>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { string _k0;  { if(!__e0[0].IsString) { throw new SerializationException(); }  _k0 = __e0[0]; } string _v0;  { if(!__e0[1].IsString) { throw new SerializationException(); }  _v0 = __e0[1]; }  AnimationClips.Add(_k0, _v0); }   }
        { var __json0 = _buf["AudioClips"]; if(!__json0.IsArray) { throw new SerializationException(); } AudioClips = new System.Collections.Generic.Dictionary<string, string>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { string _k0;  { if(!__e0[0].IsString) { throw new SerializationException(); }  _k0 = __e0[0]; } string _v0;  { if(!__e0[1].IsString) { throw new SerializationException(); }  _v0 = __e0[1]; }  AudioClips.Add(_k0, _v0); }   }
    }

    public static RoleRes DeserializeRoleRes(JSONNode _buf)
    {
        return new role.RoleRes(_buf);
    }

    public readonly int Id;
    public readonly string Name;
    public readonly string Prefab;
    public readonly string HeadIcon;
    public readonly System.Collections.Generic.Dictionary<string, string> AnimationClips;
    public readonly System.Collections.Generic.Dictionary<string, string> AudioClips;
   
    public const int __ID__ = -369051982;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Name:" + Name + ","
        + "Prefab:" + Prefab + ","
        + "HeadIcon:" + HeadIcon + ","
        + "AnimationClips:" + Luban.StringUtil.CollectionToString(AnimationClips) + ","
        + "AudioClips:" + Luban.StringUtil.CollectionToString(AudioClips) + ","
        + "}";
    }
}

}

