
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;
using UnityEngine;


namespace cfg.Role
{
public partial class TbCombo : IVOFun
{
    private readonly System.Collections.Generic.List<Role.BnCombo> _dataList;

    private System.Collections.Generic.Dictionary<(int, int), Role.BnCombo> _dataMapUnion;
    
    public TbCombo()
    {
        _dataList = new System.Collections.Generic.List<Role.BnCombo>(); 
        _dataMapUnion = new System.Collections.Generic.Dictionary<(int, int), Role.BnCombo>();
    }

    public System.Collections.Generic.List<Role.BnCombo> DataList => _dataList;

    public Role.BnCombo Get(int SkillID, int ComboID) => _dataMapUnion.TryGetValue((SkillID, ComboID), out Role.BnCombo __v) ? __v : null;
    

    public void _LoadData()
    {
        
        JSONNode _buf = JSON.Parse(GetJson("role_tbcombo"));
        foreach(JSONNode _ele in _buf.Children)
        {
            Role.BnCombo _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = Role.BnCombo.DeserializeBnCombo(_ele);  }
            _dataList.Add(_v);
            _dataMapUnion.Add((_v.SkillID, _v.ComboID), _v);
            _v.ResolveRef();
        }
    }

    private string GetJson(string fileName)
    {
        var textAsset = AssetSystem.LoadAsset<TextAsset>($"TableData/{fileName}.json");
        return textAsset.text;
    }
}

}

