
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;
using UnityEngine;


namespace cfg.role
{
public partial class TbRoleRes : IVOFun
{
    private readonly System.Collections.Generic.Dictionary<int, role.RoleRes> _dataMap;
    private readonly System.Collections.Generic.List<role.RoleRes> _dataList;
    
    public TbRoleRes()
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, role.RoleRes>();
        _dataList = new System.Collections.Generic.List<role.RoleRes>();
    }

    public System.Collections.Generic.Dictionary<int, role.RoleRes> DataMap => _dataMap;
    public System.Collections.Generic.List<role.RoleRes> DataList => _dataList;

    public role.RoleRes GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public role.RoleRes Get(int key) => _dataMap[key];
    public role.RoleRes this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }


    public void _LoadData()
    {
        
        JSONNode _buf = JSON.Parse(GetJson("role_tbroleres"));
        foreach(JSONNode _ele in _buf.Children)
        {
            role.RoleRes _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = role.RoleRes.DeserializeRoleRes(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    private string GetJson(string fileName)
    {
        var textAsset = AssetSystem.LoadAsset<TextAsset>($"TableData/{fileName}.json");
        return textAsset.text;
    }
}

}

