
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.Skill
{
public sealed partial class BoxCollider : ShapeCollider
{
    public BoxCollider(JSONNode _buf)  : base(_buf) 
    {
        { if(!_buf["Rotation"].IsObject) { throw new SerializationException(); }  Rotation = vector3.Deserializevector3(_buf["Rotation"]);  }
        { if(!_buf["Scale"].IsObject) { throw new SerializationException(); }  Scale = vector3.Deserializevector3(_buf["Scale"]);  }
    }

    public static BoxCollider DeserializeBoxCollider(JSONNode _buf)
    {
        return new Skill.BoxCollider(_buf);
    }

    public readonly vector3 Rotation;
    public readonly vector3 Scale;
   
    public const int __ID__ = 1105196674;
    public override int GetTypeId() => __ID__;

    public override void ResolveRef(Tables tables)
    {
        base.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "Position:" + Position + ","
        + "Rotation:" + Rotation + ","
        + "Scale:" + Scale + ","
        + "}";
    }
}

}

