
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.Skill
{
public sealed partial class BoxSkillCollider : ShapeCollider
{
    public BoxSkillCollider(JSONNode _buf)  : base(_buf) 
    {
        { if(!_buf["Rotation"].IsObject) { throw new SerializationException(); }  Rotation = ExternalTypeUtil.NewVector3(vector3.Deserializevector3(_buf["Rotation"]));  }
        { if(!_buf["Scale"].IsObject) { throw new SerializationException(); }  Scale = ExternalTypeUtil.NewVector3(vector3.Deserializevector3(_buf["Scale"]));  }
    }

    public static BoxSkillCollider DeserializeBoxSkillCollider(JSONNode _buf)
    {
        return new Skill.BoxSkillCollider(_buf);
    }

    public readonly UnityEngine.Vector3 Rotation;
    public readonly UnityEngine.Vector3 Scale;
   
    public const int __ID__ = 669413271;
    public override int GetTypeId() => __ID__;

    public override void ResolveRef()
    {
        base.ResolveRef();
    }

    public override string ToString()
    {
        return "{ "
        + "Position:" + Position + ","
        + "Rotation:" + Rotation + ","
        + "Scale:" + Scale + ","
        + "}";
    }
}

}

