
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.Skill
{
public sealed partial class CircleSkillCollider : ShapeCollider
{
    public CircleSkillCollider(JSONNode _buf)  : base(_buf) 
    {
        { if(!_buf["Radius"].IsNumber) { throw new SerializationException(); }  Radius = _buf["Radius"]; }
    }

    public static CircleSkillCollider DeserializeCircleSkillCollider(JSONNode _buf)
    {
        return new Skill.CircleSkillCollider(_buf);
    }

    public readonly float Radius;
   
    public const int __ID__ = 97439512;
    public override int GetTypeId() => __ID__;

    public override void ResolveRef(Tables tables)
    {
        base.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "Position:" + Position + ","
        + "Radius:" + Radius + ","
        + "}";
    }
}

}

