
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.Skill
{
public abstract partial class ColliderBase : Luban.BeanBase
{
    public ColliderBase(JSONNode _buf) 
    {
    }

    public static ColliderBase DeserializeColliderBase(JSONNode _buf)
    {
        switch ((string)_buf["$type"])
        {
            case "WeaponCollider": return new Skill.WeaponCollider(_buf);
            case "BoxSkillCollider": return new Skill.BoxSkillCollider(_buf);
            case "CircleSkillCollider": return new Skill.CircleSkillCollider(_buf);
            case "FanSkillCollider": return new Skill.FanSkillCollider(_buf);
            default: throw new SerializationException();
        }
    }

   

    public virtual void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "}";
    }
}

}

