
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.Skill
{
public abstract partial class ShapeCollider : ColliderBase
{
    public ShapeCollider(JSONNode _buf)  : base(_buf) 
    {
        { if(!_buf["Position"].IsObject) { throw new SerializationException(); }  Position = vector3.Deserializevector3(_buf["Position"]);  }
    }

    public static ShapeCollider DeserializeShapeCollider(JSONNode _buf)
    {
        switch ((string)_buf["$type"])
        {
            case "BoxSkillCollider": return new Skill.BoxSkillCollider(_buf);
            case "CircleSkillCollider": return new Skill.CircleSkillCollider(_buf);
            case "FanSkillCollider": return new Skill.FanSkillCollider(_buf);
            default: throw new SerializationException();
        }
    }

    public readonly vector3 Position;
   

    public override void ResolveRef(Tables tables)
    {
        base.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "Position:" + Position + ","
        + "}";
    }
}

}

