
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.Skill
{
public sealed partial class SkillCustomEvent : Luban.BeanBase
{
    public SkillCustomEvent(JSONNode _buf) 
    {
        { if(!_buf["EventType"].IsNumber) { throw new SerializationException(); }  EventType = (Skill.SkillEventType)_buf["EventType"].AsInt; }
    }

    public static SkillCustomEvent DeserializeSkillCustomEvent(JSONNode _buf)
    {
        return new Skill.SkillCustomEvent(_buf);
    }

    public readonly Skill.SkillEventType EventType;
   
    public const int __ID__ = 1037515989;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "EventType:" + EventType + ","
        + "}";
    }
}

}

