
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg.Skill
{ 
    public enum SkillEventType
    {
        /// <summary>
        /// 自定义事件
        /// </summary>
        Custom = 0,
        /// <summary>
        /// 可打断技能事件
        /// </summary>
        CanSkillRelease = 1,
        /// <summary>
        /// 可技能时旋转事件
        /// </summary>
        CanRotate = 2,
        /// <summary>
        /// 不可技能时旋转事件
        /// </summary>
        CanNotRotate = 3,
    }

} 

