
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.Skill
{
public sealed partial class SkillAnimationEvent : Luban.BeanBase
{
    public SkillAnimationEvent(JSONNode _buf) 
    {
        { if(!_buf["AnimationClip"].IsString) { throw new SerializationException(); }  AnimationClip = _buf["AnimationClip"]; }
        { if(!_buf["TransitionTime"].IsNumber) { throw new SerializationException(); }  TransitionTime = _buf["TransitionTime"]; }
    }

    public static SkillAnimationEvent DeserializeSkillAnimationEvent(JSONNode _buf)
    {
        return new Skill.SkillAnimationEvent(_buf);
    }

    public readonly string AnimationClip;
    public readonly float TransitionTime;
   
    public const int __ID__ = -1169960246;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "AnimationClip:" + AnimationClip + ","
        + "TransitionTime:" + TransitionTime + ","
        + "}";
    }
}

}

