
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.Skill
{
public sealed partial class SkillColliderEvent : Luban.BeanBase
{
    public SkillColliderEvent(JSONNode _buf) 
    {
        { if(!_buf["FrameIndex"].IsNumber) { throw new SerializationException(); }  FrameIndex = _buf["FrameIndex"]; }
        { if(!_buf["DurationFrame"].IsNumber) { throw new SerializationException(); }  DurationFrame = _buf["DurationFrame"]; }
        { if(!_buf["ColliderData"].IsObject) { throw new SerializationException(); }  ColliderData = Skill.ColliderBase.DeserializeColliderBase(_buf["ColliderData"]);  }
    }

    public static SkillColliderEvent DeserializeSkillColliderEvent(JSONNode _buf)
    {
        return new Skill.SkillColliderEvent(_buf);
    }

    public readonly int FrameIndex;
    public readonly int DurationFrame;
    public readonly Skill.ColliderBase ColliderData;
   
    public const int __ID__ = -1242271950;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef()
    {
        ColliderData?.ResolveRef();
    }

    public override string ToString()
    {
        return "{ "
        + "FrameIndex:" + FrameIndex + ","
        + "DurationFrame:" + DurationFrame + ","
        + "ColliderData:" + ColliderData + ","
        + "}";
    }
}

}

