
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.Skill
{
public sealed partial class SkillEffectEvent : Luban.BeanBase
{
    public SkillEffectEvent(JSONNode _buf) 
    {
        { if(!_buf["FrameIndex"].IsNumber) { throw new SerializationException(); }  FrameIndex = _buf["FrameIndex"]; }
        { if(!_buf["EffectPrefab"].IsString) { throw new SerializationException(); }  EffectPrefab = _buf["EffectPrefab"]; }
        { if(!_buf["Position"].IsObject) { throw new SerializationException(); }  Position = ExternalTypeUtil.NewVector3(vector3.Deserializevector3(_buf["Position"]));  }
        { if(!_buf["Rotation"].IsObject) { throw new SerializationException(); }  Rotation = ExternalTypeUtil.NewVector3(vector3.Deserializevector3(_buf["Rotation"]));  }
        { if(!_buf["Scale"].IsObject) { throw new SerializationException(); }  Scale = ExternalTypeUtil.NewVector3(vector3.Deserializevector3(_buf["Scale"]));  }
        { if(!_buf["Duration"].IsNumber) { throw new SerializationException(); }  Duration = _buf["Duration"]; }
        { if(!_buf["AutoDestroy"].IsBoolean) { throw new SerializationException(); }  AutoDestroy = _buf["AutoDestroy"]; }
    }

    public static SkillEffectEvent DeserializeSkillEffectEvent(JSONNode _buf)
    {
        return new Skill.SkillEffectEvent(_buf);
    }

    public readonly int FrameIndex;
    public readonly string EffectPrefab;
    public readonly UnityEngine.Vector3 Position;
    public readonly UnityEngine.Vector3 Rotation;
    public readonly UnityEngine.Vector3 Scale;
    public readonly int Duration;
    public readonly bool AutoDestroy;
   
    public const int __ID__ = 181330613;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef()
    {
    }

    public override string ToString()
    {
        return "{ "
        + "FrameIndex:" + FrameIndex + ","
        + "EffectPrefab:" + EffectPrefab + ","
        + "Position:" + Position + ","
        + "Rotation:" + Rotation + ","
        + "Scale:" + Scale + ","
        + "Duration:" + Duration + ","
        + "AutoDestroy:" + AutoDestroy + ","
        + "}";
    }
}

}

