
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.Skill
{
public sealed partial class SkillAudioEvent : Luban.BeanBase
{
    public SkillAudioEvent(JSONNode _buf) 
    {
        { if(!_buf["FrameIndex"].IsNumber) { throw new SerializationException(); }  FrameIndex = _buf["FrameIndex"]; }
        { if(!_buf["AudioClip"].IsString) { throw new SerializationException(); }  AudioClip = _buf["AudioClip"]; }
    }

    public static SkillAudioEvent DeserializeSkillAudioEvent(JSONNode _buf)
    {
        return new Skill.SkillAudioEvent(_buf);
    }

    public readonly int FrameIndex;
    public readonly string AudioClip;
   
    public const int __ID__ = -45580360;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "FrameIndex:" + FrameIndex + ","
        + "AudioClip:" + AudioClip + ","
        + "}";
    }
}

}

