
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;
using UnityEngine;


namespace cfg.Skill
{
public partial class TbSkillClip : IVOFun
{
    private readonly System.Collections.Generic.Dictionary<int, Skill.SkillClip> _dataMap;
    private readonly System.Collections.Generic.List<Skill.SkillClip> _dataList;
    
    public TbSkillClip()
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, Skill.SkillClip>();
        _dataList = new System.Collections.Generic.List<Skill.SkillClip>();
    }

    public System.Collections.Generic.Dictionary<int, Skill.SkillClip> DataMap => _dataMap;
    public System.Collections.Generic.List<Skill.SkillClip> DataList => _dataList;

    public Skill.SkillClip GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public Skill.SkillClip Get(int key) => _dataMap[key];
    public Skill.SkillClip this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }


    public void _LoadData()
    {
        
        JSONNode _buf = JSON.Parse(GetJson("skill_tbskillclip"));
        foreach(JSONNode _ele in _buf.Children)
        {
            Skill.SkillClip _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = Skill.SkillClip.DeserializeSkillClip(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.SkillID, _v);
        }
    }

    private string GetJson(string fileName)
    {
        var textAsset = AssetSystem.LoadAsset<TextAsset>($"TableData/{fileName}.json");
        return textAsset.text;
    }
}

}

