
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.Skill
{
public sealed partial class WeaponCollider : ColliderBase
{
    public WeaponCollider(JSONNode _buf)  : base(_buf) 
    {
        { if(!_buf["WeaponName"].IsString) { throw new SerializationException(); }  WeaponName = _buf["WeaponName"]; }
    }

    public static WeaponCollider DeserializeWeaponCollider(JSONNode _buf)
    {
        return new Skill.WeaponCollider(_buf);
    }

    public readonly string WeaponName;
   
    public const int __ID__ = 1879385005;
    public override int GetTypeId() => __ID__;

    public override void ResolveRef()
    {
        base.ResolveRef();
    }

    public override string ToString()
    {
        return "{ "
        + "WeaponName:" + WeaponName + ","
        + "}";
    }
}

}

