
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg
{ 
    public enum ItemQuality
    {
        /// <summary>
        /// 白
        /// </summary>
        WHITE = 0,
        /// <summary>
        /// 绿
        /// </summary>
        GREEN = 1,
        /// <summary>
        /// 红
        /// </summary>
        RED = 2,
    }

} 

