
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;

namespace cfg
{

public interface IVOFun
{
    void _LoadData();
}

public partial class Tables
{
    public TbUIWnd TbUIWnd {get; }

    public Tables(){}
    
    private void ResolveRef()
    {
        TbUIWnd.ResolveRef(this);
    }
}

}
