
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;
using UnityEngine;


namespace cfg
{
public partial class TbUIWnd : IVOFun
{
    private readonly System.Collections.Generic.Dictionary<string, UIWnd> _dataMap;
    private readonly System.Collections.Generic.List<UIWnd> _dataList;
    
    public TbUIWnd()
    {
        _dataMap = new System.Collections.Generic.Dictionary<string, UIWnd>();
        _dataList = new System.Collections.Generic.List<UIWnd>();
    }

    public System.Collections.Generic.Dictionary<string, UIWnd> DataMap => _dataMap;
    public System.Collections.Generic.List<UIWnd> DataList => _dataList;

    public UIWnd GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public UIWnd Get(string key) => _dataMap[key];
    public UIWnd this[string key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }


    public void _LoadData()
    {
        
        JSONNode _buf = JSON.Parse(GetJson("tbuiwnd"));
        foreach(JSONNode _ele in _buf.Children)
        {
            UIWnd _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = UIWnd.DeserializeUIWnd(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Name, _v);
        }
    }

    private string GetJson(string fileName)
    {
        var textAsset = AssetSystem.LoadAsset<TextAsset>($"TableData/{fileName}.json");
        return textAsset.text;
    }
}

}

