
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;

namespace cfg
{
public partial class Tables
{
    public TbTest1 TbTest1 {get; }
    public TbTest2 TbTest2 {get; }
    public TbTest3 TbTest3 {get; }

    public Tables(System.Func<string, JSONNode> loader)
    {
        TbTest1 = new TbTest1(loader("tbtest1"));
        TbTest2 = new TbTest2(loader("tbtest2"));
        TbTest3 = new TbTest3(loader("tbtest3"));
        ResolveRef();
    }
    
    private void ResolveRef()
    {
        TbTest1.ResolveRef(this);
        TbTest2.ResolveRef(this);
        TbTest3.ResolveRef(this);
    }
}

}
