
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public partial class TbTest2
{
    private readonly System.Collections.Generic.Dictionary<int, Test2> _dataMap;
    private readonly System.Collections.Generic.List<Test2> _dataList;
    
    public TbTest2(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, Test2>();
        _dataList = new System.Collections.Generic.List<Test2>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            Test2 _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = Test2.DeserializeTest2(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, Test2> DataMap => _dataMap;
    public System.Collections.Generic.List<Test2> DataList => _dataList;

    public Test2 GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public Test2 Get(int key) => _dataMap[key];
    public Test2 this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

